live_config_reload = true

[colors.cursor]
cursor = "0xcc1111"
text = "0x181818"

[colors.primary]
background = '#000000'
foreground = '#ffffff'

# Normal colors
[colors.normal]
black = '#2e3436'
red = '#cc0000'
green = '#4e9a06'
yellow = '#c4a000'
blue = '#3465a4'
magenta = '#75507b'
cyan = '#06989a'
white = '#d3d7cf'

[colors.bright]
black = '#555753'
red = '#ef2929'
green = '#8ae234'
yellow = '#fce94f'
blue = '#729fcf'
magenta = '#ad7fa8'
cyan = '#34e2e2'
white = '#eeeeec'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'

#[cursor.style]
#shape = "underline"

[env]
TERM = "xterm-256color"

[font]
size = 9
offset.x = 0
offset.y = 1

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
dynamic_padding = false
#opacity = 0.90
decorations = "transparent"
padding = { x = 4, y = 4 }

[window.dimensions]
columns = 100
lines = 30

[cursor]
style = "Beam"
