[colors.cursor]
cursor = "0xcc1111"
text = "0x181818"

[colors.primary]
background = "0x010101"

[colors.normal]
black = "#414141"
red = "#e17373"
green = "#94b978"
yellow = "#ffb97b"
blue = "#96bddb"
magenta = "#e1c0fa"
cyan = "#00988e"
white = "#dedede"

[colors.bright]
black = "#9d9d9d"
red = "#ffa0a0"
green = "#bddeab"
yellow = "#ffdba0"
blue = "#b1d7f6"
magenta = "#fbdaff"
cyan = "#19b2a7"
white = "#ffffff"

[cursor.style]
shape = "underline"

[env]
TERM = "xterm-256color"
#WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 8

[font.normal]
family = "Noto Sans Mono"
style = "Medium"

[window]
dynamic_padding = false
opacity = 0.9

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 8
y = 8
