live_config_reload = true

[colors.cursor]
cursor = "0xcc1111"
text = "0x181818"

[colors.primary]
background = "0x010101"

[colors.normal]
black = "#414141"
red = "#e17373"
green = "#94b978"
yellow = "#ffb97b"
blue = "#96bddb"
magenta = "#e1c0fa"
cyan = "#00988e"
white = "#dedede"

[colors.bright]
black = "#9d9d9d"
red = "#ffa0a0"
green = "#bddeab"
yellow = "#ffdba0"
blue = "#b1d7f6"
magenta = "#fbdaff"
cyan = "#19b2a7"
white = "#ffffff"

[cursor.style]
shape = "underline"

[env]
TERM = "xterm-256color"

[font]
size = 15
offset.x = 0
offset.y = 1

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Option"

[window]
dynamic_padding = false
opacity = 0.90
decorations = "transparent"

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 25
y = 25

